### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [GBGitUser/codacademy-teacozy#1]
Overall excellent, you matched the spec and went beyond that.

Your html and css is well organized.  You have comments through out to indicate each section.  

You use classes to maintain your code.  Your css did not have any unneeded repetition.

I didn't see or find any glaring issues.

As a challenge and to prepare you for the final set of projects, use media queries to make this website work properly on a mobile device. The final few projects will be using this heavily.

**Comment by GBGitUser** [comment]
Will do Farish - thanks for the positive feedback. :)
